version: '3.6'
services:
  sennder_api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: sennder_api
    restart: unless-stopped
    expose:
        - 80
        - 443
    volumes:
      - ./api:/app:cached
    environment:
      LETSENCRYPT_HOST: api.sennder.abdulwahid.info
      VIRTUAL_HOST: api.sennder.abdulwahid.info
    
  sennder_webapp:
    build:
        context: ./webapp
        dockerfile: ./Dockerfile
    container_name: sennder_webapp
    restart: unless-stopped
    expose:
        - 80
        - 443
    volumes:
        - ./webapp/:/app:cached
        - /app/node_modules/
    environment:
        LETSENCRYPT_HOST: sennder.abdulwahid.info
        VIRTUAL_HOST: sennder.abdulwahid.info

volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
