version: '3.6'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api
    restart: unless-stopped
    ports: 
        - '8000:80'
    expose:
        - 80
    volumes:
      - ./api:/app:cached
    
  webapp:
    build:
        context: ./webapp
        dockerfile: ./Dockerfile
    container_name: webapp
    restart: unless-stopped
    ports: 
        - '8080:80'
    expose:
        - 80
    volumes:
        - ./webapp/:/app:cached
        - /app/node_modules/
