version: '3.6'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api
    restart: unless-stopped
    expose:
        - 80
        - 443
    volumes:
      - ./api:/app:cached
    environment:
      LETSENCRYPT_HOST: api.sennder.abdulwahid.info
      VIRTUAL_HOST: api.sennder.abdulwahid.info
    
  webapp:
    build:
        context: ./webapp
        dockerfile: ./Dockerfile
    container_name: webapp
    restart: unless-stopped
    expose:
        - 80
        - 443
    volumes:
        - ./webapp/:/app:cached
        - /app/node_modules/
    environment:
        LETSENCRYPT_HOST: sennder.abdulwahid.info
        VIRTUAL_HOST: sennder.abdulwahid.info

volumes:
  db_data:

# networks:
#   default:
#     external:
#       name: nginx-proxy
